### ISSUE TITLE
Syntax error in example YAML file?

### ISSUE THREAD

**Issue by peterdesmet** [gbif/dwca-validator#23]
I've just tried:

> java -jar target/dwca-validator.jar -c examples/FileBasedValidationChain.yaml -s http://data.inbo.be/ipt/archive.do?r=kevers-grensmaas-occurrences

And got:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" Cannot create property=rowTypeRestriction for JavaBean=org.gbif.dwc.validator.criteria.configuration.CompletenessCriterionConfiguration@2974baa
 in 'reader', line 6, column 6:
       - !completenessCriterionConfiguration
         ^
No single argument constructor found for interface org.gbif.dwc.terms.Term
 in 'reader', line 8, column 29:
         rowTypeRestriction			: 'http://rs.tdwg.org/dwc/terms/Oc ... 
                                ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:307)
```

I'm not sure what the error is exactly or how to fix it.

**Comment by cgendreau** [comment]
yes there is a syntax error in the file. Fixed: https://github.com/gbif/dwca-validator/commit/bda0c5e76bca5689a79ca01d2aeee64ae822d6af

Thanks for reporting it

**Comment by cgendreau** [comment]
Please note that this example of configuration also uses a dictionary file for basisOfRecord that is not provided.
`# The dictionary file must exist, path can be absolute or relative to the app location`

**Comment by peterdesmet** [comment]
I see you fixed this on the `master` branch, while [you advise in the wiki](https://github.com/gbif/dwca-validator/wiki/CommandLine#build-from-source) to use the `dev` branch. Which one should I use?

**Comment by peterdesmet** [comment]
Regarding your comment, is that why I see `Can't read dictionary file at basis_of_record.txt`?  Wouldn't it be useful to include this in `examples`?

**Comment by cgendreau** [comment]
Wiki is now fixed, the master branch should be used.
As for the dictionary file I agree, a basic one should be included.

Originally, I wanted to let people build their own file from the documentation in the wiki but it quickly became a complicated and tedious task because well, it is not easy to configure. So I`m now changing the approach with a working example that people could edit to fit their needs. It will also probably accept configuration as json in the future.

**Comment by cgendreau** [comment]
Apparently someone (me) already added that 1 year ago:
https://github.com/gbif/dwca-validator/tree/master/dwca-validator-lib/examples
