### ISSUE TITLE
Relationship to http://tools.gbif.org/dwca-validator/

### ISSUE THREAD

**Issue by niconoe** [gbif/dwca-validator#25]
Does this tool plan to replace the online validator at http://tools.gbif.org/dwca-validator/, or will the two projects coexists? If so, what's the status of http://tools.gbif.org/dwca-validator/? Should people still use it? 

I ask because I identified issues in this old validator (basically, it accepts some Archive I consider as quite invalid, so people complain to me that https://github.com/BelgianBiodiversityPlatform/python-dwca-reader/ doesn't support those -supposedly valid) archives.

Thanks a lot!

**Comment by mdoering** [comment]
we plan to eventually replace the current online validator, yes. But that is not any time soon and the project is maintained here meanwhile: https://github.com/gbif/dwca-validator3

If you spot bugs please file them there
