### ISSUE TITLE
Question about uniqueness criterion

### ISSUE THREAD

**Issue by hettling** [gbif/dwca-validator#26]
Hi @cgendreau,

I was trying out the stand-alone validation tool on some test data and get errors for violating uniqueness constraints on some 180 records of ~35000 records in total, e.g. 

    RMNH.MAM.1156.b,uniquenessCriterion,CORE,,uniqueness,ERROR,The value RMNH.MAM.1156.b was already used for term coreId
    RMNH.MAM.12579.b,uniquenessCriterion,CORE,,uniqueness,ERROR,The value RMNH.MAM.12579.b was already used for term coreId

However, when I do a grep on the IDs (e.g. RMNH.MAM.1156.b) I see that they are unique in the file.

Am I missing something?

Here is my test data:
https://github.com/hettling/api-datatest/blob/master/t/testdata/mammalia.zip

and I called the program as follows: `java -jar dwca-validator-lib/target/dwca-validator.jar -s ~/Downloads/mammalia.zip `

Hope you can give some advice,
Best,

Hannes

**Comment by cgendreau** [comment]
Hi @hettling ,

The comparaison is applied ignoring the 'case' which means that, in the provided file, `RMNH.MAM.1156.b` is considered the same as `RMNH.MAM.1156.B`.

This may not be the expected behavior. It is mostly to avoid relying on the 'case' of a letter to define the uniqueness of an identifier. The same approach is used in the DOI[1] system.

**Comment by mdoering** [comment]
@cgendreau I would also vote for case sensitive uniqueness. This is what our code does and most id systems incl even urls, uris

**Comment by cgendreau** [comment]
We could, of course there is no technical limitation and everything would work. I'm simply not convinced it's always good idea. But it could be optional for sure, we just need to define the default value.

**Comment by hettling** [comment]
Hi @cgendreau,

thanks for investigating this issue, this revealed some issue in our export pipeline, since the entries are actually the same. So the case-sensitive check really helped.
